services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
