# Generated by Django 2.2.11 on 2020-07-08 11:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagedata',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
