# Generated by Django 2.2.11 on 2020-07-06 20:35

import Rasta_Web.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(blank=True, help_text='برای نمایش بهتر در سایت، باید نسبت ابعاد تصویر بین ۰.۸ تا ۱.۲ باشد.', null=True, upload_to='blog/', validators=[Rasta_Web.utils.validate_image_size, Rasta_Web.utils.validate_square_image]),
        ),
    ]
