# Generated by Django 2.2.11 on 2020-07-08 11:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200706_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
