# Generated by Django 2.2.11 on 2020-09-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='shortened_url',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
