# Generated by Django 2.2.11 on 2020-07-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastamember',
            name='photo_hidden',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
