# Generated by Django 3.1.5 on 2022-01-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_auto_20200704_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RastaMember',
        ),
    ]
