# Generated by Django 2.2.11 on 2020-09-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20200915_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='date_unsubsscribed',
            new_name='date_unsubscribed',
        ),
    ]
